<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'application/index/foo'          => __DIR__ . '/view/application/index/foo.php',
    'application/index/index'        => __DIR__ . '/view/application/index/index.phtml',
    'application/index/foo.phtml'    => __DIR__ . '/view/application/index/foo.phtml.bak',
    'application/widgets/top_left'   => __DIR__ . '/view/application/widgets/top_left.phtml',
    'application/widgets/lower_left' => __DIR__ . '/view/application/widgets/lower_left.phtml',
    'error/index'                    => __DIR__ . '/view/error/index.phtml',
    'error/404'                      => __DIR__ . '/view/error/404.phtml',
    'layout/layout'                  => __DIR__ . '/view/layout/layout.phtml',
    'scripts/something/foo'          => __DIR__ . '/view/scripts/something/foo.phtml',
);
